import { GetStaticProps } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import React from 'react';

import styles from './styles.module.scss';

const Checkout = () => {
  return (
    <>
      <Head>
        <title>Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.mainBox}>
        <div className={styles.contentBox}>
          <div className={styles.content}>
            <div className={styles.infoBox}>
              <h2>Checkout</h2>

              <h3>Sua hospedagem</h3>

              <div className={styles.infoHolder}>
                <div>
                  <h4>Datas</h4>
                  <h5>23 - 29 de mai.</h5>
                </div>
                <div>
                  <h4>Total Hóspedes</h4>
                  <h5>12</h5>
                </div>
              </div>

              <div
                className={styles.infoHolder}
                style={{ flexDirection: 'column' }}
              >
                <h4>Previsão de chegada</h4>
                <input type="text" />
              </div>
            </div>
            <div className={styles.ctaBoxHolder}>
              <div className={styles.ctaBox}>
                <div></div>
              </div>
            </div>
          </div>
          <div className={styles.mobInfoPriceContainer}>
            <h3>Informações de preço</h3>
            <div className={styles.mobInfoHolder}>
              <div>
                <u>
                  {' '}
                  <h5>Hospedagem 18 noites</h5>
                </u>
              </div>
              <div>
                <u>
                  {' '}
                  <h5>R$98,00</h5>
                </u>
              </div>
            </div>
            <div className={styles.mobInfoHolder}>
              <div>
                <u>
                  {' '}
                  <h5>Hospedagem 18 noites</h5>
                </u>
              </div>
              <div>
                <u>
                  {' '}
                  <h5>R$98,00</h5>
                </u>
              </div>
            </div>

            <div className={styles.mobInfoTotalHolder}>
              <div>
                <h5>Total(BRL)</h5>
              </div>
              <div>
                <h5>R$198,00</h5>
              </div>
            </div>

            <div className={styles.mobMoreInfoHolder}>
              <u>
                <h5 style={{ alignSelf: 'center' }}>Mais informações</h5>
              </u>
            </div>
          </div>

          <div className={styles.mobPersonalDataContainer}>

          </div>
        </div>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
    },
    revalidate: 60,
  };
};

export default Checkout;
