import { Head } from 'next/document';
import React from 'react';

import styles from './styles.module.scss';

const Checkout = () => {
  return (
    <>
      <Head>
        <title>Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Checkout;
