import React from 'react';
import Head from 'next/head';
import styles from './search.module.scss';
import { HotelOutlined, AttractionsOutlined } from '@mui/icons-material';
import CardRoom from '../../components/CardRoom';
const Search = () => {
  return (
    <>
      <Head>
        <title>Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className={styles.headerSection}></header>
        <section className={styles.filterInfo}>
          <div style={{ minHeight: 96, maxHeight: 96, width: '100%' }}></div>

          <div style={{ flex: 1, paddingTop: 16 }}>
            <h2>
              <span>03</span> quartos com <span>06</span> serviços foram
              encontrados
            </h2>
          </div>
          <div className={styles.filtersMobileSection}>
            <div
              style={{
                borderBottom: '6px solid black'
              }}
              className={styles.filterButtonContainer}
            >
              <HotelOutlined style={{ marginBottom: '0.2rem' }} />
              <h4>Quartos</h4>
            </div>
            <div
              style={{ opacity: 0.35, paddingBottom: '1.4rem' }}
              className={styles.filterButtonContainer}
            >
              <AttractionsOutlined style={{ marginBottom: '0.2rem' }} />
              <h4>Serviços</h4>
            </div>
          </div>
        </section>
        <section className={styles.contentResultContainer}>
          <CardRoom />
          <CardRoom />
          <CardRoom />
          <CardRoom />
          <CardRoom />
          <CardRoom />
        </section>
      </main>
    </>
  );
};

export default Search;
